### ISSUE TITLE
Pre-Release going the totally wrong way..

### ISSUE THREAD

**Issue by xlovinglyx** [RealRaven2000/FiltaQuilla#110]
https://github.com/RealRaven2000/FiltaQuilla/files/6800329/filtaquilla-3.2pre30.zip

body filtering is still inactive. & body filtering isn't that "javascript application" popping in an unrequested way & inactive too,
but filtering based on one line based regex.

**Comment by RealRaven2000** [comment]
Can you clarify? I don't understand this; maybe reference the other issue that you got the pre-release version from... there is probably  a reason why you picked this one?

Also please adjust the title to be a little more concrete. 
- Previews? not sure what previews and how this relates to filters 
- "going the wrong way" again this is too broad. When you use the term "preview" I think of the preview pane underneath the emails list, bet you meant something different

if you can add 2 sections
- observed  behavior
- expected behavior

thanks in advance!

**Comment by xlovinglyx** [comment]
Simple: that preview build has an ineffective "body regex action". but after months & months of waiting, 
i'm not surprised to see this as a "workaround". the effect is nonsensical on tb.

**Comment by xlovinglyx** [comment]
& you should know what's wrong, the way it's been coded is totally useless. adding body regex can be a very small step
& understood but the result is totally spacedout, displaced & unrequested. we're all expecting online based regexes & not a "javascript application" that you'll see during your test since the package was released ... .

**Comment by RealRaven2000** [comment]
why don't you comment on the original issue? #75 where it was posted. No need to open new issues to complain about a version that is posted elsewhere.

**Comment by RealRaven2000** [comment]
I put a new version at #75 please comment there

**Comment by xlovinglyx** [comment]
please look at it, looks like noone saw it & there's no assignee:

https://github.com/RealRaven2000/FiltaQuilla/issues/87

**Comment by RealRaven2000** [comment]
> please look at it, looks like noone saw it & there's no assignee:
> 
> #87

I have seen it, but I am still on the fence, as it's a super specialized feature (not helping many users) and very difficult to program on top.

**Comment by xlovinglyx** [comment]
I don't understand your reluctance cause this will clearly fight numerous & numerous clearly spam related emails
hands down, eyes closed.. so if by this response ur not gonna look at it, please be honest, so i'll keep asking it
to other extension coders, which will complicate more the situation but it's a must have feature for me, as you
already know that too many spams are based on not using the To field.

So this mention makes me sadly smile: "(not helping many users)".

**Comment by RealRaven2000** [comment]
> I don't understand your reluctance cause this will clearly fight numerous & numerous clearly spam related emails
> hands down, eyes closed..

FiltaQuilla isn't primarily created as a spam handling tool, it's more for managing the emails you want to get. Trying to handle Spam with address filters is a loosing battle in an arms race - it's better to use the heuristic (Junk control) and Spam measures by your email provider.

> so if by this response ur not gonna look at it, please be honest, so i'll keep asking it
> to other extension coders...

yes you should. I may look at this later but I have other priorities like making my Add-ons work with Thunderbird 91. If you add a new issue, which you are welcome too, be assured that I see it (I get an email for every issue and comment) and if you do not see immediate response, just send a follow up on the same issue, rather than commenting elsewhere, because that's just messy, and issues aren't rally designed as an email system. You use #110 twice now to point to other issues (#87 and #75), please don't do that in the future just stick to 1 new feature / bug per issue. If you don't see engagement after a long time feel free to either write another comment on the issue or send me an email, but be assured that I read all my emails related to my Add-on issues. 

Unfortunately Filtaquilla is not monetized so as regards new features I will always give my commercial Add-ons first treatment. Also I do get emails / feedback for my Add-ons via Email, and I hadn't got your suggestion from any other users. Who is to know whether FiltaQuilla is used for handling Spam in this very specific way by other users? we always think our own use case is the most important, but we sadly cannot implement absolutely every possible functionality because it will make the coding too much work (especially for free as in beer) and the tool very hard to configure for the majority of users.

**Comment by xlovinglyx** [comment]
"it's better to use the heuristic (Junk control) and Spam measures by your email provider."

compared to what i exactly requested ? come on lol, it's like requiring a car & getting a boat..
they both have gas in common, but they're not used for the same purpose ((

im not gonna ravage myfilters by "the heuristic lotto", & it's not the goal, if i was a heuristic spam control fan,
i wouldnt even be requesting body regex filtering ))

"I may look at this later"

then i'll wait.
