### ISSUE TITLE
Save Message as File doesn't work with illegal filename characters in subject as "\", ":", "*", "|" or "?"

### ISSUE THREAD

**Issue by SmilySunMike** [RealRaven2000/FiltaQuilla#144]
if the Subject="EG:MySubject" only a filename EG is created because the double point let the action fail.

Solution: Delete all illegal file characters "\", ":", "*", "|" or "?" before creating the file.

**Comment by RealRaven2000** [comment]
It should actually  already do this according to the function _sanitizeName() which is called on the subject - it should remove all characters except the following:

"-abcdefghijklmnopqrstuvwxyz0123456789"

so I would expect this to create the name with the  ":" omitted. The original  function is by Kent James though so I need to check whether something has changed in it. Are you using the latest version of FiltaQuilla?

**Comment by RealRaven2000** [comment]
@SmilySunMike  see comment above - are you using the latest version (3.2) ?

**Comment by SmilySunMike** [comment]
Yes, I'm using FiltaQuila 3.2

**Comment by RealRaven2000** [comment]
I just did a test and was able to generate an exception.
My original Subject line was:

[fq #144] - message: with delimiter / | or wildcard ? * characters

IN the error log I can see the attempt to save it as this file name:
Could not create file with name:[fq-#144]---message--with-delimiter-----or-wildcard-?-*-char.eml

so it looks like the : was replaced but not the ? or * wildcards.

**Comment by RealRaven2000** [comment]
I changed the algorithm a little, not sure if file names have to be stricly lowercase, so I am allowing that too. * and ? will now also be replaced with - (rather than dropped); Diacritics and Umlauts such as  À, ã, Č, ņ etc will be replaced phonetically similar to this [stack overflow article](https://stackoverflow.com/questions/45863899/cant-manage-to-remove-diacritics-from-a-filename).

[filtaquilla-3.3pre30.zip](https://github.com/RealRaven2000/FiltaQuilla/files/7897557/filtaquilla-3.3pre30.zip)

To install, download the zip file and (without extracting) drag into Thunderbird Add-ons manager.

**Comment by PalmBeachPop** [comment]
I just found that I have this problem, too.  The message subject has a colon, to wit: "Famous Alerts: Account Summary".  
 filtaquilla-3.3pre30 did not solve the problem.

**Comment by RealRaven2000** [comment]
did you try to restart Thunderbird? I tested a subject specifically with
":" in it.  if it still fails please check error console (Ctrl +Shift +J)
it should show the file name it tries to save

**Comment by PalmBeachPop** [comment]
I had munged the filter.  It's working now.  Thanks RealRaven2000!

**Comment by SmilySunMike** [comment]
Perfect, version 3.3pre3.0 works for me. Thank you very much!

**Comment by RealRaven2000** [comment]
Fixed in 3.3, officially released today (21/02/22)
