### ISSUE TITLE
Action 'Save Message as a File' fails again in version 3.3, if email subject contains a colon ':'

### ISSUE THREAD

**Issue by LittleAlf** [RealRaven2000/FiltaQuilla#150]
This issue was reported to be solved as mentioned in #53.

Unfortunately, in the newest version of FiltaQuilla 3.3, it is popping up again: The email subject is "ING: Umsatz gebucht", and the filter just creates an empty file in the target directory with 'ING' as filename:

![Zwischenablage02](https://user-images.githubusercontent.com/25395270/151672402-e6167a7c-2e5f-4c51-9c8f-51deb42f2546.jpg)

I can confirm, that this failure is related to the colon in the subject. If I change the email subject to one without a colon, the 'Save Message as a File' action works.

Is it possible to check the related parser, if the colon is still in the list of characters to be replaced by '-'?

Any help would be really appreciated.

**Comment by RealRaven2000** [comment]
I have tested with my latest current beta version:

[filtaquilla-3.3.1pre15.zip](https://github.com/RealRaven2000/FiltaQuilla/files/7964334/filtaquilla-3.3.1pre15.zip)

The subject line of the message was:
[fq #144] - message: with delimiter / | or wildcard ? * characters

it creates a file titled
fq-144---message--with-delimiter-----or-wildcard-----charact.eml

instead of using a blacklist it goes through the 2 steps - phonetic replacement of special characters, replacement of 
@ :  | / \ * ?  with -

then only alphanumeric (ASCII) and - characters are being used everything else is dropped and the string is cut of after 60 characters. These are the only characters that are "let through" for generating a file name:

"-ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

The function that does all this work is called `_sanitizeName( )` and is identical in FQ 3.3. Did you make sure to restart Thunderbird in case the old function was still in the cache?

**Comment by LittleAlf** [comment]
Sorry, sorry, sorry: The old version was still in the cache! (I didn't restart the PC overnight.) :( :( :(

Issue closed.
