### ISSUE TITLE
Subject & Content (Regular expression) - missing Textbox

### ISSUE THREAD

**Issue by Saibot521** [RealRaven2000/FiltaQuilla#178]
Thunderbird 102.3.1 (64-Bit)
FiltaQuilla 3,5
Language: German (de-DE)

I want to set a Filter for Junk and want to use the Filter "Subject & Content (Regular expression)
![grafik](https://user-images.githubusercontent.com/114833603/193427747-518dd103-ab9e-493a-aeab-efaa7e644e3e.png)

I have found an Error - Missing text box to enter the Reglar Expression

**Comment by RealRaven2000** [comment]
I think this may be a regression with Thunderbird 102 - quickFix version here:

[filtaquilla-3.5.1pre16.zip](https://github.com/RealRaven2000/FiltaQuilla/files/9692497/filtaquilla-3.5.1pre16.zip)

I also fixed the width issue for the textboxes only being shown 140px wide. To install, download the zip file above and drag into Thunderbird Add-ons Manager (do not unpack contents to install it).

**Comment by RealRaven2000** [comment]
I think this may be a regression with Thunderbird 102 - quickFix version here:

[filtaquilla-3.5.1pre17.zip](https://github.com/RealRaven2000/FiltaQuilla/files/9692513/filtaquilla-3.5.1pre17.zip)


I also fixed the width issue for the textboxes only being shown 140px wide. To install, download the zip file above and drag into Thunderbird Add-ons Manager (do not unpack contents to install it).

Note: previous version pre16 had a problem due to a broken build.bat - I had a powershell script for building that I could not repair due to upgrading  my machine to Windows10. I don't remember who made it for me, so I switched back to my old build batch method that uses a text file to store revisions.

**Comment by Saibot521** [comment]
Thanks for Patch, but i have the same problem.
I select "Inhalt" (Content) ... 
then i switch to "Betreff oder Inahlt (Regulärer Ausdruck)" (Subject & Content Regular Expression)
... there is no textbox to enter the regular expression

**Comment by RealRaven2000** [comment]
yeah only works when you reopen the dialog - try this one please:

[filtaquilla-3.5.1pre22.zip](https://github.com/RealRaven2000/FiltaQuilla/files/9693291/filtaquilla-3.5.1pre22.zip)

**Comment by Saibot521** [comment]
Now it works, thanks

**Comment by RealRaven2000** [comment]
Included in release 3.6, published on 17/10.
