### ISSUE TITLE
Ability to remove regexp from message body

### ISSUE THREAD

**Issue by averter** [RealRaven2000/FiltaQuilla#182]
This feature seems so natural to have that I feel silly asking, but, can we define a filter that removes a regexp from a message body? That is, the message will be displayed without the matched regions. If this is not possible with FiltaQuilla is there any other add-on which can do the job? Thank you in advance.

**Comment by RealRaven2000** [comment]
when you say removes something from a message - you mean modifying the mail and then saving it like that? The only thing you can do is use a SmartTemplate and forward / reply with that, SmartTemplates has plenty of methods of modifying the original (quoted) message.

**Comment by averter** [comment]
> when you say removes something from a message - you mean modifying the mail and then saving it like that? The only thing you can do is use a SmartTemplate and forward / reply with that, SmartTemplates has plenty of methods of modifying the original (quoted) message.

I'd be happy even with just displaying it without the matched regions (no altering needed) if possible. Being able to reply to the email without the matched regions in the quoted message would be a great bonus as well; thanks for pointing out the SmartTemplates (will have a look into that). Is there any future plans to add such feature? Thanks!

**Comment by RealRaven2000** [comment]
> I'd be happy even with just displaying it without the matched regions (no altering needed) if possible. 

Displaying an email (e.g. in a new tab) is not a good fit for a filter action, as it can potentially overwhelm the UI and crash Thunderbird - because it may find 100s of matches. Filters usually do things like add tags, move / copy mail, archive mails or do other follow up actions that should not require user interaction.

> Being able to reply to the email without the matched regions in the quoted message would be a great bonus as well; thanks for pointing out the SmartTemplates (will have a look into that). Is there any future plans to add such feature? Thanks!

it's very unlikely that this is going to be implemented because filters usually work on (potentially many) emails in the background. I think your request is super specialised and I cannot see that it would benefit a large number of users. Can you give more detail on how you would use such a feature in practice? It sounds like you basically want to transform / censor all incoming emails in some way... which could be achieved with a different kind of Add-on that doesn't use the filtering mechanism at all but just messes with the message preview pane in some way.

**Comment by averter** [comment]
Good point! A use case of such feature is helpful indeed.

Nowadays companies add a disclaimer header to emails that come from outside the company. For example
```
("This message originated outside of "Insert Company Name". Use caution when opening attachments, clicking links or responding to requests for information.")
```
and for someone who receives many external emails it becomes quite annoying to keep watching the same header over and over. Not to mention that links from inside of a company are not necessarily safe :-P. So it would be great if this could be removed/hidden.

**Comment by RealRaven2000** [comment]
I think it would be a good idea for its own Add-on, but it cannot be provided by FiltaQuilla. If I were to create it properly I would base this on regular expressions and add a collapsed section to the previewed email that could be expanded if necessary.
