### ISSUE TITLE
Save attachments to - not working as expected in TB 102.4.1 & FiltaQuilla 3.6.1

### ISSUE THREAD

**Issue by simion-chis** [RealRaven2000/FiltaQuilla#191]
Hi,
I've seen that are few issue with saving attachments. In my case I have a filter to save a file like "Raport-mfp-2022-11-01.xlsx" and then delete the email. The folder is 100% mounted (/home/username/Downloads)

At the **first start**  of TB (in morning) the filter just delete the email (attachment is not saved). If I move email from trash back into inbox the same filter work as expected. 

But more strange/interesting is the following: now the email is in trash, I close TB, I open webmail and move email from trash to inbox, I open TB and filter work as expected (it save the attachment and delete email). So, only at the first start (a "cold start") the filter is not working properly.
TB 102.4.1 with FiltaQuilla 3.6.1 is installed on Pop!_OS 22.04

**Comment by RealRaven2000** [comment]
Strange - did you make sure no other filters deleted the mail (did you check the filter log)? It seems that the attachments are probably not fully downloaded when Thunderbird starts, which is obviously a problem with Thunderbird itself. But then they never planned to save attachment during filtering, so it's also hard to blame them; might be a good idea to log some bugs in Bugzilla for Tb because FiltaQuilla doesn't really have any influence on the whole timing aspect of things. The actual filter mechanism runs deep in the guts of compiled code (C++).

**Comment by simion-chis** [comment]
> did you make sure no other filters deleted the mail (did you check the filter log)? 

I have no other filters and I've also checked the filter log. Everything looks ok. See the attached image. I have three emails in total, one attachment per email and one filter for every email.
![Selection_004](https://user-images.githubusercontent.com/45000352/199669412-d35390f4-61d6-4ded-9828-1c3f998e4b5f.jpg)


I think that this issue can be closed because I don't see a pattern.  Eg. in this morning files was saved for every filter but only one email was deleted. So, _delete_ action does not worked this time. The other two emails are still in inbox. As you said, maybe is something in Thunderbird.

Thank you!

**Comment by simion-chis** [comment]
I will close this thread because of the inconsistency of this issue.
