### ISSUE TITLE
Filters dosn't work on Thunderbird 102.4.2 (32 bites)

### ISSUE THREAD

**Issue by DPappD** [RealRaven2000/FiltaQuilla#193]
I made two different filter for mail but dosn't work any.

**Comment by RealRaven2000** [comment]
> I made two different filter for mail but dosn't work any.

something doesn't work, that's not even near enough info to help or look into.

More detail please? maybe screenshots of the filter definitions or write down conditions and actions, also whether the filters run automatically, and whether before or after Junk classification.

**Comment by DPappD** [comment]
![Képernyőkép 2022-11-10 123134](https://user-images.githubusercontent.com/117909358/201080148-690012c9-b407-4ab5-be69-583faa2ebf49.png)
![Képernyőkép 2022-11-10 123149](https://user-images.githubusercontent.com/117909358/201080153-8b491250-5ec0-4037-ba2a-69dceff54ae5.png)

**Comment by DPappD** [comment]
![Képernyőkép 2022-11-10 123415](https://user-images.githubusercontent.com/117909358/201080845-f6ab7e11-7361-4ae6-9724-577564ab489c.png)
![Képernyőkép 2022-11-10 123541](https://user-images.githubusercontent.com/117909358/201080850-5d832867-4caa-44d3-90d5-3bc1c9128f4c.png)

**Comment by RealRaven2000** [comment]
Thanks for providing translated screenshots. try setting the filter "Getting new mail" setting to run _after Junk classificiation_. You can also check whether the filter attempted to run using the Filter Log (bottom right of the message filtes window):

![image](https://user-images.githubusercontent.com/6314674/201083507-5808f9c2-3d8d-425f-b49a-30dc06934628.png)

There are 2 possibilities:

- the search term / filter condition didn't trigger (subject contains ...) due to problems with encoding
- saving the data didn't work

Can you run the filter manually? If it doesn't run, check error console:

Press `Ctrl`+`Shift`+`J`

- Clear the output before you run the filter
![image](https://user-images.githubusercontent.com/6314674/201083999-4e31c012-bc86-4aa7-b8d5-0ca62bd8fb73.png)

- Capture the log with right-click / Copy all Messages:
![image](https://user-images.githubusercontent.com/6314674/201084151-186130f0-b0cf-4689-8f9c-2e7a3b26ed31.png)

**Comment by DPappD** [comment]
The problem is solved!
The mistake was that the filter was "for" a wrong folder.

**Comment by RealRaven2000** [comment]
ok. I guess that means the folder needed repair or wasn't an inbox... (remember only inbox folders can execute filters automatically)

**Comment by DPappD** [comment]
The filters weren't connect to the mail box in Thunderbord but also "local folder".
That was the problem.

**Comment by DPappD** [comment]
Thank you for everything
Bye
