### ISSUE TITLE
Printing fails in 3.7

### ISSUE THREAD

**Issue by gitFrank** [RealRaven2000/FiltaQuilla#217]
Can it be or is it only to me. Since 3.7 the printing is stopped.
Manually executing the filter shows a error message ala "printing not possible".
How can i get the version before 3.7 and how can i downgrade?

**Comment by RealRaven2000** [comment]
- Can you make a screenshot of the message? 
- Have a look at error console (CTRL+Shift+J) any errors there when you run the filter?

You could also try with the [Add-on PrintingTools NG](https://addons.thunderbird.net/thunderbird/addon/printingtools-ng/

and the option for NG enabled:

![image](https://user-images.githubusercontent.com/6314674/227218853-f69698ff-93ff-4d78-8aad-7145ebe08894.png)

**Comment by RealRaven2000** [comment]
OK, here is an attempt at a bugfix:

[filtaquilla-3.7.1pre3.zip](https://github.com/RealRaven2000/FiltaQuilla/files/11051918/filtaquilla-3.7.1pre3.zip)

To install this version, download the zip file above, then drag the file into Thunderbird Add-ons Manager. Do not extract its contents because then it won't install.

**Comment by gitFrank** [comment]
Seems this works (after restart). Printing starts. *thumb up*
I'm sure in the tab "Filter Actions" was more as two checkboxes checked before. Is this only in your fix so or will it be in the next update the same?
Thank you for the very fast fix.

**Comment by RealRaven2000** [comment]
> I'm sure in the tab "Filter Actions" was more as two checkboxes checked before. Is this only in your fix so or will it be in the next update the same?

no I never put fixes in the release versions (sarcasm off).  ;-)

Sorry of course if I fix something it goes straight into the next release version, you can just keep running the prerelease and it will be automatically replaced with the release because of the version numbering rules in Thunderbird: 

3.7.1 > 3.7.1preXXX

**Comment by RealRaven2000** [comment]
Fixed in 3.7.1 released today (23/03/2023)
