### ISSUE TITLE
Question re: run periodlcally, every 10 minutes

### ISSUE THREAD

**Issue by ksihota** [RealRaven2000/FiltaQuilla#232]
Is there any way to change the ten minutes to a user specified time?
every 10 minutes is a little too often for a cleanup filter. Once every hour or once a day would be nice or a field to just enter a time frame?

Just realized that this is a desktop client not a server setup so 10 minutes would be a reasonable time since most people don't leave their desktop systems running 24/7

Don't see how to delete this now. Sorry just ignore it or remove it if you can.

**Comment by RealRaven2000** [comment]
I think you can influence the (global) filter period with the following setting in about:config

`mail.server.default.periodicFilterRateMinutes`

it's a "one period fits all" setting, and it is the only way at the moment in Thunderbird (the filtering happens partly in the compiled background) - it is hard to implement a filter-specific attribute like this because there is no built in way to store this against the filter (additional attributes not supported), and if we wanted to manage it from the outside, the filters do not have unique identifiers, which is a big problem with adding any functionality other than custom search terms and custom actions. You would only be able to match your info via server + filter name and that info is not unique to a filter. 

(You can have multiple filters with the exact same name)
