### ISSUE TITLE
Regular expressions gone with Thunderbird 128.2.3esr

### ISSUE THREAD

**Issue by mlw-x** [RealRaven2000/FiltaQuilla#299]
QuickFilters: 6.5.3
Thunderbird: 128.2.3esr

After updating to Thunderbird 128.2.3esr, quickFilters stopped executing a filter including a regex match of the email subject. The UI shows the respective search term as "missing":

![image](https://github.com/user-attachments/assets/fa7f2fce-0d33-4a60-bb42-bb86d34f895f)

However, when exporting the filters, the search term is still present:

```json
{
  "attrib": -2,
  "op": 19,
  "value": {
    "attrib": -2,
    "str": "/(rechnung|invoice|zahlung|payment|transa[ck]tion|billing)/i"
  },
  "booleanAnd": true,
  "customId": "filtaquilla@mesquilla.com#subjectRegex",
  "beginsGrouping": false,
  "endsGrouping": false
},
````

It is also not possible to select regex matches when creating or editing filters.

**Comment by RealRaven2000** [comment]
I have transferred the issue here to the FiltaQuilla Github, because quickFilters is not involved during _filter execution_. Regular expressions are added by FiltaQuilla, even if you used quickFilters to generate the new filter.

I think you will find that if you reinstall / enable FiltaQuilla and make sure that in its options you enable regex search, the filter will work again:

![image](https://github.com/user-attachments/assets/ab5b4aeb-f8c9-4549-a302-79d0cd4be232)


by the way, after a big update of Tb (e,g, 102 t o128) it sometimes reports ADd-ons as incompatible without update, I made a video on this and how to fix it here:

https://youtu.be/4woIJZ2tDDQ

**Comment by RealRaven2000** [comment]
Just to make sure, I tested regular expression in subject on the beta 131.0b5 as well, where it worked fine for me.

![image](https://github.com/user-attachments/assets/7cb9e9a0-532f-4c3e-9316-411dca5c935e)

**Comment by mlw-x** [comment]
Thank you for your super quick response. Indeed it seemed that after the Thunderbird update the FiltaQuilla extension was disabled for some reason, which in turn was causing the issue.

So I guess this is unrelated to quickFilters and can be closed.

**Comment by RealRaven2000** [comment]
> Thank you for your super quick response. Indeed it seemed that after the Thunderbird update the FiltaQuilla extension was disabled for some reason, which in turn was causing the issue.
> 
> So I guess this is unrelated to quickFilters and can be closed.

ok will do. thanks to being a full-time Add-on Dev, I check my Github daily, so no big deal.
