### ISSUE TITLE
"Save Message As File" no longer works as of 4.1 (TB 128.3) - error code 0x80570021

### ISSUE THREAD

**Issue by petenish** [RealRaven2000/FiltaQuilla#306]
I got updated to 4.1 recently (running TB 128.3.1esr) and "Save Messages A File" saves an empty file ("(No Sender) (No Subject)").   Pretty sure this worked before the upgrade.  Couldn't go back to 4.0 as TB complains about version skew.
I've tried different settings (like junk filter stuff).
Debug log says (with REDACTED that I put in for privacy)

[10/15/24, 7:41:58 AM GMT-4] Filter action failed: "filterActionFailed" with error code=0x80570021 while attempting: Applied filter "REDACTED" to message from REDACTED at 10/15/24, 7:32:08 AM GMT-4 Save Message as File 

Any help/hints/suggestions here?

**Comment by RealRaven2000** [comment]
Can you capture an error log on console?

https://quickfilters.quickfolders.org/bugs.html

instead of enabling the debug mode in quickFilters you can find the Debug mode of FiltaQuilla on the About / Help page in FiltaQuilla settings:

![image](https://github.com/user-attachments/assets/970041f6-c83c-446b-8df2-16fd832b39cc)

If you can run the filter manually on the specific email and reproduce the error it would be most helpful - you can reset the console output before you test to minimize the amount of data I need to look through...

also please try whether the version at #270 fixes the problem.

**Comment by petenish** [comment]
I set the debug checkbox, but (I'm sorry to be so dumb), but I don't know where the "console" output resides.  The log output is the same.
Also, #270 mentions a .zip file, but I don't know how to "install" the contents to TB.  Any help here?

**Comment by RealRaven2000** [comment]
> I set the debug checkbox, but (I'm sorry to be so dumb), but I don't know where the "console" output resides. 

The easiest way to get it is by pushing CTRL+Shift+J (as [described here](https://quickfilters.quickfolders.org/bugs.html))

![image](https://github.com/user-attachments/assets/c8757fc7-7ca9-4fbf-b65d-b3a7d9ccde28)

Another way is via the Thunderbird Main menu (press Alt+T for tools popup in case the main menu is not displayed)
![image](https://github.com/user-attachments/assets/cca01b84-3ba6-4c76-a077-4a0e4bd41b27)

then select Developer Tools >> Error Console



> The log output is the same. Also, #270 mentions a .zip file, but I don't know how to "install" the contents to TB. Any help here?

It said it: To try the version above **download zip file and drag the file into Thunderbird Add-ons Manager** (do not extract contents, it won't install like that) - so just right-click the aforementioned zip and save as... so you have a copy on disk. The zip file can then be dragged into Thunderbird >> Add-ons and Themes on the Extensions Tab:

![image](https://github.com/user-attachments/assets/ee426550-4579-4876-9ed6-3f858135e77f)

Important: Before testing, reset the log:

![image](https://github.com/user-attachments/assets/f20b32ee-564a-40fd-93de-735c27ce06e7)

[we don't need to see everything that happened since you started Thunderbird]

After running the filter (with the fail), right-click any message in the log and select "Copy all Messages"

![image](https://github.com/user-attachments/assets/fa387a56-e3bf-4634-9fc4-1b66ff9deb54)

then you can paste the results here - or send them to me via support link in case there are privacy issues with the content. Typically you may see some red messages that show errors but the context before that is important too.

**Comment by zimmerik** [comment]
I also have the same issue, empty file (0 B) is saved since upgrade to 4.1 on TB128.3

**Comment by RealRaven2000** [comment]
Can we get an error log from error console?

**Comment by petenish** [comment]
I mentioned this earlier (somewhere), but I found 4.2 on github and installed that and it fixed my problem

**Comment by petenish** [comment]
Here's a link:

https://github.com/RealRaven2000/FiltaQuilla/releases

**Comment by RealRaven2000** [comment]
> Here's a link:
> 
> https://github.com/RealRaven2000/FiltaQuilla/releases

I have also published 4.2 on ATN, but it is currently awaiting review, the new version will probably be reviewed and officially published later this weekend (or early next week).

**Comment by RealRaven2000** [comment]
> I mentioned this earlier (somewhere), but I found 4.2 on github and installed that and it fixed my problem

Ok I mark this one as complete with 4.2 (released 15/10/2023)
