### ISSUE TITLE
Configuration not visible

### ISSUE THREAD

**Issue by DRESAAN** [RealRaven2000/FiltaQuilla#6]
The default filters are shown in the filter configuration. But I'm unable to open the FiltaQuilla configuration to enable more. There is no configuration button as seen in the screenshot:

![2019-02-20_08h23_31](https://user-images.githubusercontent.com/6796885/53073617-d3ae8e00-34e8-11e9-8548-dbae8665ae0f.png)

**Comment by DRESAAN** [comment]
ok, my fault. I'm sorry.

**Comment by RealRaven2000** [comment]
Hey not to worry. It was just one of the design decisions taken in Mozilla that was heavily disputed (I didn't like it at all) but I decided to go along with it rather than swimming against the stream - as there are much more important issues such as XUL support and XPCOM access without which our Add-ons wouldn't work at all.
