### ISSUE TITLE
Will FQ be updated for TB versions greater than 73.0?

### ISSUE THREAD

**Issue by fade2gray** [RealRaven2000/FiltaQuilla#66]
Hi, looking for a header regex search tool.

**Comment by RealRaven2000** [comment]
Are you asking 2 questions in one here? Make that 2 issues, please, or change the title.

FQ will be updated for Tb78, once I am finished converting all my commercial Add-ons. That will hopefully also pay for FiltaQuilla. If not, then I will try to find somebody else to take it over.

**Comment by RealRaven2000** [comment]
I have just updated #64 - that's where I will track all conversion efforts for Thunderbird 78 (the next ESR period) - just leave a comment there to see the news.

Please bear in mind that the ESR for Thunderbird 68 is still active right now. You should not be auto-updated to 78 unless you are on some weird Linux Distro. Thunderbird is actively stopping Tb from being automatically rolled out through it's update mechanism - it shouldn't happen until mid / late September.

**Comment by fade2gray** [comment]
Thanks for the reply,

I have only just installed TB to import an unwieldy gmail account, and while I find TB's search filter capabilities far superior to gmail's default it still lacks the refinement of regex search.

A web search gave me the impression that FQ would suit my needs.

**Comment by RealRaven2000** [comment]
> 
> 
> Thanks for the reply,
> 
> I have only just installed TB to import an unwieldy gmail account, and while I find TB's search filter capabilities far superior to gmail's default it still lacks the refinement of regex search.
> 
> A web search gave me the impression that FQ would suit my needs.

Then try these settings:
![image](https://user-images.githubusercontent.com/6314674/90559811-157bcb80-e196-11ea-943e-135dbe41354a.png)

important notes: 
- you need to activate them first and restart Thunderbird in order to use them in the filter dialog
- if you disable the Add-on (or update to Tb78) the filters will stop working, they need the Add-on in good working order to work
- you can look up the documentation by clicking the little blue question mark beside the options (if it has one)
well embarrassingly that feature is broken since we migrated the web sites from the free (and now retired) server at mozdev.org, here are the corrected links:

http://quickfilters.quickfolders.org/filtaquilla.html#subject_regex
http://quickfilters.quickfolders.org/filtaquilla.html#header_regex

I think that should cover the bases. Most importantly, will I be able to convert it for Tb78? They are closing all sorts of doors on the Mozilla side at the moment and Tb is just stumbling after to fix stuff and (very maybe) open a few doors back up for us Add-on authors. You wouldn't believe how much time I invest talking to the Tb Core team to make sure we still have a "back door" for our own shit.

**Comment by fade2gray** [comment]
Where would we be without the likes of you and other devs who put in so much for so little in return.

Thank you.

**Comment by RealRaven2000** [comment]
Closing as resolved with the following release:
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/3.0.2.0
