### ISSUE TITLE
Save Attachment filter option disapeared Thunderbird V.78.2.2 (32bit)

### ISSUE THREAD

**Issue by SrConserje** [RealRaven2000/FiltaQuilla#70]
Hello.
Save attachment filter option disapeared after updating Thunderbird to the latest version.
FitaQuilla is enabled.
As you can see in the screenshots, we use Thunderbird in spanish. Before the update, save attachment option appeared at the bottom of the action list, in english.
Any ideas on how to solve this issue?
Thanks, regards.
![01](https://user-images.githubusercontent.com/71432871/93447111-56b8e580-f8d2-11ea-916a-6ba89bbd0bf7.jpg)
![02](https://user-images.githubusercontent.com/71432871/93447126-59b3d600-f8d2-11ea-82cd-d24d58637542.jpg)

**Comment by RealRaven2000** [comment]
> 
> 
> Hello.
> Save attachment filter option disapeared after updating Thunderbird to the latest version.

> As you can see in the screenshots, we use Thunderbird in spanish. Before the update, save attachment option appeared at the bottom of the action list, in english.
> Any ideas on how to solve this issue?

FiltaQuilla **is not (yet) compatible** with Thunderbird 78, it will be converted eventually (once my commercial Add-ons QuickFolders / quickFilters and SmartTemplate are done). We already 200 hours in, so we will have to do some fund raising to ensure being able to convert the other Add-ons.

please leave a comment here to be notified:
[issue 64](https://github.com/RealRaven2000/FiltaQuilla/issues/64)

**Comment by SrConserje** [comment]
Hello:
Thanks for replying. How much funds do you need to get FiltaQuilla working on Thunderbird's last update?
Greetings,

--
Enviado desde la aplicación myMail para Android jueves, 17 septiembre 2020, 00:58p. m. +02:00 de RealRaven2000  notifications@github.com :

**Comment by RealRaven2000** [comment]
> 
> Hello: Thanks for replying. How much funds do you need to get FiltaQuilla working on Thunderbird's last update? Greetings,
> […](#)

It's hard to say but I would think around 15-40 hours of work and testing (400 to 1000 euro to fund development). If I have enough time I will do it myself (for free), but this is unlikely because I also have to put quite a bit of work into support etc. for my commercial Add-ons, and then there is a the music studio. Unfortunately there are very few specialists who are willing to work on this type of code and I think most of them work for Thunderbird itself so they wouldn't really have time to work on a 3rd party Add-on.
