### ISSUE TITLE
Attachment content empty

### ISSUE THREAD

**Issue by Alaindeg** [RealRaven2000/FiltaQuilla#84]
Hello,

I've made a rule to put the attachments files on my desktop for a specified sender when I check my mails.
The attachment is a .csv file.
When I check my mails, it 's well put on the desktop but it 's empty.

When I select the mail and ask in the Tools menu to apply the filters on the message, the attachment is  put on the desktop and  its content is correct.

Amazing  no ?

If you want I can send you the concerned files.

Thank you

Alain

**Comment by RealRaven2000** [comment]
The files won't help me - one thing you might try is to set the filter up to "run after junk controls". The other one is looking at JavaScript error console after Get Mail. Tools / Developer Tools / Error Console - in error console, you can right-click and export all visible messages to clipboard which gives us a nice readable log. Also, enable the debug mode checkbox in FiltaQuilla before you run the test, which may give a little additional info:

![image](https://user-images.githubusercontent.com/6314674/102888747-48d6ab80-4451-11eb-907d-2204f53a165c.png)

Generally speaking Imap is a bitch with attachments, it may just not have been downloaded fully and it's hard to tell when the mail is ready; that's why I suspect it works.

**Comment by Alaindeg** [comment]
Thank you, 

After setting the filter up to "run after junk controls", it works !
Happy NewYear !

Alain
