### ISSUE TITLE
Two issues: Missing options menu and (temporarily) missing Regex search

### ISSUE THREAD

**Issue by sometimegithubuser** [RealRaven2000/FiltaQuilla#99]
Maybe I'm missing something, but I think there are two issues with the version of FiltaQuilla I have installed which is the 3.1Pre24 version provided to enable ToneQuilla. I'm running TB 78.8.1.

The first is that the Add-on Options menu is missing for FiltaQuilla:

![image](https://user-images.githubusercontent.com/24495871/111090038-93be0780-8504-11eb-954f-c358fe8f0f5d.png)

The options are there on the three dots button in the Add-ons Manager:

![image](https://user-images.githubusercontent.com/24495871/111090283-9a00b380-8505-11eb-9016-67af268c66db.png)

The second issue is that I have checked the "Header Regex Match" box, but didn't see that option offered in filters as an option in a new filter I was creating thru quickFilters Assistant. In fact none of the FiltaQuilla options were present. But when I just re-opened a new filter I created today and clicked on the filter drop-down, all the FiltaQuilla options were present, including Header Regex Match. The only thing I can think of is that I've had two TB crashes today trying to use quickFilters Assistant. In both cases I allowed the crash box to restart TB, tried the same operation again, and it worked without a crash. So maybe filtaQuilla was temporarily disabled after the 1st crash???

**Comment by RealRaven2000** [comment]
The first one is by design, see also the version notes:
https://quickfilters.quickfolders.org/fq-versions.html#3.1

I am using John Bieling's Window Loader experimental API and he updated it to be more conform with other Add-ons from THunderbird 78 going forward. Same change will be applied to all my Add-ons, so eventually the Tools / Add-ons menu is going away. (We can't have both ways).

As regards filtaquilla not bein available the only way you can check at the moment is by having the error console open and looking out for messages (while you are going the the assistant)... it may help to activate the "debug" option on the support tab of FIltaQuilla options:

![image](https://user-images.githubusercontent.com/6314674/111151662-acbbcc80-8587-11eb-9c8a-2e6ae0e80c9e.png)
this will add some additional logs about filtaquilla's activities.

PS: If you add more issue, please make them single issues don't bundle up multiple things into the same item.
